all: pos sonar laser	

pos:	
	gcc -o pos position2d.c -I/usr/local/include/player-3.0 -L/usr/local/lib64 -lplayerc

sonar:	
	gcc -o sonar sonar.c -I/usr/local/include/player-3.0 -L/usr/local/lib64 -lplayerc

laser:	
	gcc -o laser laser.c -I/usr/local/include/player-3.0 -L/usr/local/lib64 -lplayerc


